market_place/market_place/urls.py
# """
# URL configuration for market_place project.
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views.static import serve


urlpatterns = [
    path("", include("shop.urls")),
    path("orders/", include("order.urls")),
    path("baskets/", include("basket.urls")),
    path("auth/", include("authorization.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    urlpatterns += staticfiles_urlpatterns()

else:
    urlpatterns += (
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    )

market_place/shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from market_place.settings import CACHE_SECONDS

from .views import (
    GroupProductListView,
    TopSellerProductListView,
    ProductDetailView,
)


app_name = "shop"

urlpatterns = [
    path(
        "",
        cache_page(CACHE_SECONDS)(TopSellerProductListView.as_view()),
        name="top_seller_product",
    ),
    path(
        "products?pk=<int:pk>/",
        cache_page(CACHE_SECONDS)(ProductDetailView.as_view()),
        name="product_details",
    ),
    path(
        "categories?category=<str:category>&groups=<str:group>/",
        cache_page(CACHE_SECONDS)(GroupProductListView.as_view()),
        name="group_product_list_view",
    ),
]

market_place/shop/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = "id", "name"

    name = models.CharField(max_length=50, blank=False, unique=True)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name


class Group(models.Model):
    class Meta:
        verbose_name = "Group"
        verbose_name_plural = "Groups"
        ordering = "id", "name"

    name = models.CharField(max_length=50, blank=False)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="names"
    )

    def __str__(self):
        return f"Группа= {self.name}, категория={self.category})"


def prod_photo_directory_path(instance: "Product", filename: str) -> str:
    return f"photo_prod/product_{instance.pk}/photo/{filename}"


class Product(models.Model):
    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"
        ordering = "id", "name"

    name = models.CharField(max_length=50, blank=False)
    price = models.DecimalField(null=False, max_digits=8, decimal_places=2, blank=False)
    size = models.CharField(max_length=5, blank=True)
    color = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(default=0)
    archived = models.BooleanField(default=False)
    group = models.ManyToManyField(Group, related_name="products")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(
        null=True, upload_to=prod_photo_directory_path, blank=False
    )

    def __str__(self):
        return self.name

market_place/shop/views.py
from django.db import connection
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, reverse, render, get_object_or_404
from django.views import View
from django.views.generic import (
    DetailView,
    ListView,
)

from .models import Category, Group, Product
from env_data import live_cookies
from django.db.utils import ProgrammingError

try:
    queryset_group = Group.objects.prefetch_related("category").order_by("category")

    category_dict = dict()
    for qr in queryset_group:
        category_dict.setdefault(qr.category, [])
        group_list = category_dict[qr.category]
        group_list.append(qr.name)
        category_dict[qr.category] = group_list

except ProgrammingError:
    pass

CATER_GROUP_NAV = {"category_dict": category_dict}


class TopSellerProductListView(ListView):
    model = Product
    template_name = "shop_product_list.html"
    queryset = (
        Product.objects.filter(archived=False)
        .prefetch_related("group")
        .order_by("-rating")[:10]
    )

    def get_context_data(self, **kwargs) -> dict:
        context = super(ListView, self).get_context_data(**kwargs)
        context.update(CATER_GROUP_NAV)
        context.update({"name_page": "Хиты продаж"})
        return context


class GroupProductListView(ListView):
    model = Product
    template_name = "shop_product_list.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):
        """
        Paginate by specified value in querystring, or use default class property value.
        """
        return self.request.GET.get("paginate_by", self.paginate_by)

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.category = kwargs["category"]
        self.group = kwargs["group"]
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(
                self.object_list, "exists"
            ):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_queryset(self) -> list[Product]:
        self.sql_query = f"""
        SELECT sp.id, sp.name, sp.price, sp.photo
        FROM shop_product as sp
        JOIN shop_product_group spg on sp.id = spg.product_id
        JOIN shop_group sg on sg.id = spg.group_id
        JOIN shop_category sc on sc.id = sg.category_id
        WHERE sc.name = '{self.category}' AND sg.name = '{self.group}';
            """

        with connection.cursor() as cursor:
            cursor.execute(self.sql_query)
            results = cursor.fetchall()

        class Photo:
            def __init__(self, name: str, url: str):
                self.name = name
                self.url = url

        class Product:
            def __init__(self, id: int, name: str, price: str, photo: Photo):
                self.id = id
                self.name = name
                self.price = price
                self.photo = photo

        product_list = []
        for attrs in results:
            id, name, price, photo_url = attrs
            photo = Photo(name, f"/media/{photo_url}")
            product = Product(id, name, price, photo)
            product_list.append(product)
        return product_list

    def get_context_data(self, **kwargs) -> dict:
        context = super(ListView, self).get_context_data(**kwargs)
        context.update(CATER_GROUP_NAV)
        context.update({"name_page": self.group})
        return context


class ProductDetailView(View):
    def get(self, request: HttpRequest, pk: int) -> HttpResponse:
        product = get_object_or_404(Product, pk=pk)
        context = {"object": product}
        context.update(CATER_GROUP_NAV)
        return render(request, "shop_product_details.html", context=context)

    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        value = request.COOKIES.get("basket")
        products_id = f"{value} {pk}"
        product_id_list = products_id.split(" ")

        total_price = 0
        products_list = []
        for product_id in product_id_list[1:]:
            product = Product.objects.get(id=product_id)
            products_list.append(product)
            total_price += product.price

        context = {
            "name_page": "Корзина",
            "object_list": products_list,
            "total_price": total_price,
        }
        context.update(CATER_GROUP_NAV)
        response = render(request, "basket_products_list.html", context=context)
        response.set_cookie(key="basket", value=products_id, max_age=live_cookies)
        return response

market_place/shop/templates/product_details.html
{% extends 'index.html' %}

{% block title %}
    Информация о товаре {{ object.name }}
{% endblock %}

{% block content %}
    <div class="detail_container_product">
        <img class="detail_product" src="{{ product.photo.url }}" width="256" alt="{{ product.photo.name }}" >
        <h2 class="detail_info_product">{{ object.name }}</h2>
        Описание:<em> {{ object.description }}</em>
        <br>
        Размер:<em> {{ object.size }} </em>
        <br>
        Цвет:<em> {{ object.description }}</em>
        <br>
        Рейтинг:<em> {{ object.rating }} </em>
        <br>
        Цена:<em> {{ object.price }} </em>
    </div>

    <div class="flex">
        <a href="javascript:history.back()">
            <button class="btn btn-secondary">Вернуться</button>
        </a>

        <a class="margin-left_btn" href="#GOTO_BASKET">
            <button class="btn btn-primary">Купить</button>
        </a>
    </div>
{% endblock %}

market_place/shop/templates/products_list.html
{% extends 'index.html' %}

{% block title %}
    {{ name_page.title }}
{% endblock %}

{% block name_page %}
    {{ name_page.title }}
{% endblock %}

{% block content %}
    {% for product in object_list %}
        <a class="list_product" href={% url 'shop:product_details' pk=product.id%}>
            <img class="img_product" src="{{ product.photo.url }}" width="65" alt="{{ product.photo.name }}" >

            <div class="info_product">
                {{ product.name }}
                <br>
                {{ product.price }} руб.
            </div>
        </a>
    {% endfor %}

{#    <div class="flex">#}
{#        <a href="javascript:history.back()">#}
{#            <button class="btn btn-secondary">Вернуться</button>#}
{#        </a>#}
{#    </div>#}
{% endblock %}

market_place/shop/templates/top_products_list.html
{% extends 'index.html' %}

{% block title %}
    Хиты продаж
{% endblock %}

{% block name_page %}
    Хиты продаж
{% endblock %}

{% block content %}
    {% for product in object_list %}
        <a class="list_product" href="products/{{ product.id }}">
            <img class="img_product" src="{{ product.photo.url }}" width="65" alt="{{ product.photo.name }}" >

            <div class="info_product">
                {{ product.name }}
                <br>
                {{ product.price }} руб.
            </div>
        </a>
    {% endfor %}
{% endblock %}